version: '3'
services:
    mongo:
        image: mongo:3.0
        volumes:
            - mongo-data:/data/db

    node:
        build:
            context: ./dockerfiles/node
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
        links:
            - mongo
        depends_on:
            - mongo
        environment:
            - CLOUDINARY_URL=cloudinary://THIS_IS_FAKE_TOKENBt5A@dpuh3vssk
            - MONGO_URI=mongodb://mongo/keystone
        command: "run_init"

volumes:
    mongo-data:
